using 'main.bicep'

param environmentName = 'buutdemo'
param location = 'northeurope'
param functionAppRuntime = 'custom'
param functionAppRuntimeVersion = '1.0'
param resourceGroupName = 'buutdemo'
param functionPlanName = 'buutdemo-flexconsumption'
param functionAppName = 'buutdemo-jar-service'
param storageAccountName = 'buutdemostorage2025nov'
param userAssignedIdentityName = 'buutdemo-jar-identity'
param cosmosAccountName = 'buutdemocosmosdb'
